# Site settings
title: Top English Editing 
email: stephens.claire@gmail.com
description: > # Expert editor specializing in refining translated texts for natural, fluent, and error-free English.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

LinkedIn_username: https://www.linkedin.com/in/clairestephens3/ 
github_username:top-english-editing

# Build settings
markdown: kramdown
