# Site settings
title: "Top English Editing" 
email: "stephens.claire@gmail.com"
description: "Expert editor specializing in refining translated texts for natural, fluent, and error-free English."
baseurl: "/blog" 
url: ""

github_username: "top-english-editing"

# Build settings
markdown: kramdown
